export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const CLEAR_STORE_POSTS = "CLEAR_STORE_POSTS";
export const SET_ACTIVE_POSTS_PAGE = "SET_ACTIVE_POSTS_PAGE";