export const FETCH_CREATE_POST_REQUEST = "FETCH_CREATE_POST_REQUEST";
export const FETCH_CREATE_POST_SUCCESS = "FETCH_CREATE_POST_SUCCESS";
export const FETCH_CREATE_POST_FAILURE = "FETCH_CREATE_POST_FAILURE";
export const CLEAR_CREATE_POST = "CLEAR_CREATE_POST";
export const FETCH_EDIT_POST_REQUEST = "FETCH_EDIT_POST_REQUEST";
export const FETCH_EDIT_POST_SUCCESS = "FETCH_EDIT_POST_SUCCESS";
export const FETCH_EDIT_POST_FAILURE = "FETCH_EDIT_POST_FAILURE";