export const FETCH_CREATE_POST_REQUEST = "FETCH_CREATE_POST_REQUEST";
export const FETCH_CREATE_POST_SUCCESS = "FETCH_CREATE_POST_SUCCESS";
export const FETCH_CREATE_POST_FAILURE = "FETCH_CREATE_POST_FAILURE";