export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const CLEAR_STORE_USERS = "CLEAR_STORE_USERS";
export const SET_ACTIVE_USERS_PAGE = "SET_ACTIVE_USERS_PAGE";